### ISSUE TITLE
Linking and routing

### ISSUE THREAD

**Issue by alexomon018** [voluntree-uk/app-next#53]
I have noticed that there is a use of the chakra Link component to navigate between pages. Chakra link is fine as long as it is wrapped in the next link (https://nextjs.org/docs/api-reference/next/link) which is recommended way of client-side transitions between routes.

**Comment by mika018** [comment]
I checked all the instances where chakra `<Link>` is used and in all of the cases they are either:
* using an `onClick` event that in turn calls nextjs router to navigate to a different page
* are wrapped in next link as @alexomon018 suggested

The only exceptions are all the links in the footer. 
The footer is just a placeholder atm and needs a complete rewrite, we have a separate ticket to track that, see #40. 
I made an explicit reminder there not to use chakra links with `href`.

I think this is safe to close now
